/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab;

import lab.GenericItem;
import lab.GenericItem.Category;

public class App {

    public static void main(String[] args) {
        GenericItem obj1 = new GenericItem(1, "bread", 1.2f, 3, Category.FOOD);
        GenericItem obj2 = new GenericItem(2, "short", 2.2f, 1, Category.DRESS);
        GenericItem obj3 = new GenericItem(3, "print", 3.2f, 2, Category.PRINT);

        obj1.printAll();
        obj2.printAll();
        obj3.printAll();
    }
}
